name: Deploy Snowpark Apps

# Controls when the action will run. 
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Configure snowcli
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWFLAKE_PWD: ${{ secrets.SNOWSQL_PWD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWSQL_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
        run: |
          cd $GITHUB_WORKSPACE
          echo '[connections]' > config.toml
          echo '[connections.default]' >> config.toml
          echo 'account = "$secrets.SNOWSQL_ACCOUNT"' >> config.toml
          echo 'user = "$SNOWSQL_USER"' >> config.toml
          echo 'password = "$SNOWSQL_PWD"' >> config.toml
          echo 'role = "$SNOWSQL_ROLE"' >> config.toml
          echo 'warehouse = "$SNOWSQL_WAREHOUSE"' >> config.toml
          echo 'database = "$SNOWSQL_DATABASE"' >> config.toml
          chown $USER "config.toml"
          chmod 0600 "config.toml"

      - name: Deploy Snowpark apps
        # run: python deploy_snowpark_apps.py $GITHUB_WORKSPACE
        run: python test.py $GITHUB_WORKSPACE
