name: deploy
on: [push, workflow_dispatch]
jobs:
  version:
     name: "Check Snowflake CLI version"
     runs-on: ubuntu-latest
     env:
        # SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWSQL_PWD }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ secrets.SNOWSQL_USER }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA: ${{ secrets.SNOWSQL_SCHEMA }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: ${{ secrets.SNOWSQL_ROLE }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY: ${{ secrets.SNOWSQL_RSAKEY }}
        # SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_PATH: "rsa_key.p8"
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: "SNOWFLAKE_JWT"
        RSA_KEY: ${{ secrets.SNOWSQL_RSAKEY }}



     steps:
          # Checkout step is necessary if you want to use a config file from your repo
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            persist-credentials: false

          # Snowflake CLI installation
        - uses: Snowflake-Labs/snowflake-cli-action@v1
          with:
            cli-version: "latest"
            # default-config-file-path: "config.toml"
        
          # Use the CLI
        - name: Deploy Snowpark apps
          run: |
           echo "$RSA_KEY" > rsa_key.p8
           snow --version
           snow connection test --connection="myconnection"
           snow snowpark build
           snow snowpark deploy --replace --connection="myconnection" --authenticator="SNOWFLAKE_JWT" --debug --private-key-path="rsa_key.p8"